apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: k8sworkshopharman/frontend-service:latest
          resources:
            limits:
              memory: "384Mi"
            requests:
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: workshop.backend.host
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: backend.host
            - name: workshop.backend.port
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: backend.port
            - name: workshop.username
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: username
            - name: workshop.password
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: password
            - name: JAVA_OPTS
              value: "-Xmx256m -Xms64m -Xss256k"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    run: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8888
      nodePort: 30000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  username: astronaut
  password: moon
  backend.host: backend-service
  backend.port: "8080"